# Generated by Django 5.0.6 on 2024-07-17 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consejos',
            options={'ordering': ['nombreRed'], 'verbose_name': 'Consejo', 'verbose_name_plural': 'Consejos'},
        ),
        migrations.AlterModelOptions(
            name='herramientas',
            options={'ordering': ['nombre'], 'verbose_name': 'Herramienta', 'verbose_name_plural': 'Herramientas'},
        ),
        migrations.AlterModelOptions(
            name='musica',
            options={'ordering': ['estilo'], 'verbose_name': 'Música', 'verbose_name_plural': 'Músicas'},
        ),
        migrations.AlterModelOptions(
            name='profesionales',
            options={'ordering': ['profesion'], 'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
        migrations.AddField(
            model_name='musica',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
